# secret
apiVersion: v1
kind: Secret
metadata:
  name: flask-secret
  namespace: my-app
type: Opaque
data:
  CELERY_BROKER_URL: cmVkaXM6Ly9yZWRpcy1kZXBsb3kubXktYXBwOjYzNzkvMA== # redis://redis-deploy.my-app:6379/0
  CELERY_RESULT_BACKEND: cmVkaXM6Ly9yZWRpcy1kZXBsb3kubXktYXBwOjYzNzkvMQ== # redis://redis-deploy.my-app:6379/1
